#!/bin/sh

# Variable initialization
SOURCE="$PWD"
TARGET="Publish"

pushd $PWD

abort() {
    popd
    exit 1
}

while getopts f:s:S:T:vh opt
do
    case $opt in
        f)  customFileParam=$OPTARG
            customFile=$(realpath $customFileParam);;
        s) echo "Option -s $OPTARG is not supported yet.";;
        S) SOURCE=$OPTARG;;
        T) TARGET=$OPTARG;;
        v) echo "Option -v";;
        h) echo "Option -h is not supported yet.";;
        ?) abort
    esac
done

cd "$SOURCE"
if [ $? -ne 0 ]
then
    echo Beende...
    abort
fi

if [ ! -d "$TARGET" ]
then
    mkdir "$TARGET"
    if [ $? -ne 0 ]
    then
	echo Beende...
	abort
    fi
fi

if [ $customFileParam ]
then
    if [ -f $customFile ]
    then
        FILES=$(cat $customFile)
    else
        >&2 echo $customFileParam does not exist or is not a file.
        abort
    fi
elif [ -f $TARGET.txt ]
then
    FILES=$(cat $TARGET.txt)
elif [ -f resize.txt ]
then
    FILES=$(cat resize.txt)
else
    FILES="*.JPG *.jpg"
fi

for i in $FILES
do
    echo Verkleinere $i
    convert $i -resize 2048x1536 $TARGET/$i
done

popd
